framework:
    validation:
        email_validation_mode: html5

        # Enables validator auto-mapping support.
        # For instance, basic validation constraints will be inferred from Doctrine's metadata.
        #auto_mapping:
        #    App\Entity\: []

        mapping:
            paths:
                # Common
                - '%kernel.project_dir%/src/Common/Infrastructure/Mapping/Validation/Uuid.validation.xml'

                # Client
                - '%kernel.project_dir%/src/Client/Infrastructure/Mapping/Validation/ConfirmationToken.validation.xml'
                - '%kernel.project_dir%/src/Client/Infrastructure/Mapping/Validation/Email.validation.xml'
                - '%kernel.project_dir%/src/Client/Infrastructure/Mapping/Validation/Name.validation.xml'
                - '%kernel.project_dir%/src/Client/Infrastructure/Mapping/Validation/Password.validation.xml'
                - '%kernel.project_dir%/src/Client/Infrastructure/Mapping/Validation/PlainPassword.validation.xml'

                # Admin
                - '%kernel.project_dir%/src/Admin/Infrastructure/Mapping/Validation/Admin.validation.xml'

when@test:
    framework:
        validation:
            not_compromised_password: false
